language:  java
jdk:
  - openjdk8

branches:
  only:
    - testDev

# Travis CI서버의 홈
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      -  zem95@naver.com
