spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: VTHNTNTXmceUmsAhC0ab
            client-secret: AQ8kBby2f9
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: name,email,profile_image
            client-name: Naver
          google:
            client-id: 493940272271-iffvh8t9nvkgm4074mapg8p4vk56ik20.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response