spring:
  profiles:
    include: oauth
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 493940272271-iffvh8t9nvkgm4074mapg8p4vk56ik20.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
